-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/cu_useragent.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cu_useragent (
  cuua_id BIGSERIAL NOT NULL,
  cuua_text TEXT NOT NULL,
  PRIMARY KEY(cuua_id)
);

CREATE INDEX cuua_text ON cu_useragent (cuua_text);
