-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/cuci_wiki_map.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cuci_wiki_map (
  ciwm_id SMALLSERIAL NOT NULL,
  ciwm_wiki TEXT NOT NULL,
  PRIMARY KEY(ciwm_id)
);

CREATE UNIQUE INDEX ciwm_wiki ON cuci_wiki_map (ciwm_wiki);
