-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/cuci_user.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cuci_user (
  ciu_central_id INT NOT NULL,
  ciu_ciwm_id SMALLINT NOT NULL,
  ciu_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ciu_central_id, ciu_ciwm_id)
);

CREATE INDEX ciu_timestamp ON cuci_user (ciu_timestamp);

CREATE INDEX ciu_central_id_timestamp ON cuci_user (ciu_central_id, ciu_timestamp);
