-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cu_log_event-add-index-cule_actor_ip_hex_time.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX cule_actor_ip_hex_time ON cu_log_event (
  cule_actor, cule_ip_hex, cule_timestamp
);
