-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_user-def.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cusi_user (
  siu_user_id INT NOT NULL,
  siu_sic_id INT NOT NULL,
  PRIMARY KEY(siu_sic_id, siu_user_id)
);

CREATE INDEX siu_user_id ON cusi_user (siu_user_id);
