-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cu_changes-drop-defaults.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE cu_changes
  ALTER cuc_actor
  DROP DEFAULT;
ALTER TABLE cu_changes
  ALTER cuc_comment_id
  DROP DEFAULT;
