-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_signal-def.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cusi_signal (
  sis_sic_id INT NOT NULL,
  sis_name TEXT NOT NULL,
  sis_value TEXT NOT NULL,
  PRIMARY KEY(sis_name, sis_value, sis_sic_id)
);

CREATE INDEX sis_sic_id ON cusi_signal (sis_sic_id);
