-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case-modify-sic_url_identifier.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX sic_url_identifier;

ALTER TABLE cusi_case
  ALTER sic_url_identifier
  DROP DEFAULT;

CREATE UNIQUE INDEX sic_url_identifier ON cusi_case (sic_url_identifier);
