-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case-add-sic_url_identifier.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE cusi_case
  ADD sic_url_identifier INT DEFAULT 0 NOT NULL;

CREATE INDEX sic_url_identifier ON cusi_case (sic_url_identifier);
