-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cu_log-drop-cul_user.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX cul_user;
ALTER TABLE cu_log
  DROP cul_user;
ALTER TABLE cu_log
  DROP cul_user_text;
