-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-oathauth_user_handles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/oathauth_user_handles (
  oah_user INTEGER UNSIGNED NOT NULL,
  oah_handle BLOB DEFAULT NULL,
  PRIMARY KEY(oah_user)
);

CREATE UNIQUE INDEX oah_handle ON /*_*/oathauth_user_handles (oah_handle);
