-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables-sharedtracking.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/echo_unread_wikis (
  euw_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  euw_user INTEGER UNSIGNED NOT NULL,
  euw_wiki VARCHAR(64) NOT NULL,
  euw_alerts INTEGER UNSIGNED NOT NULL,
  euw_alerts_ts BLOB NOT NULL,
  euw_messages INTEGER UNSIGNED NOT NULL,
  euw_messages_ts BLOB NOT NULL
);

CREATE UNIQUE INDEX echo_unread_wikis_user_wiki ON /*_*/echo_unread_wikis (euw_user, euw_wiki);
