-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: Math/sql/mathoid.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/mathoid (
  math_inputhash BLOB NOT NULL,
  math_input CLOB NOT NULL,
  math_tex CLOB DEFAULT NULL,
  math_mathml CLOB DEFAULT NULL,
  math_svg CLOB DEFAULT NULL,
  math_style SMALLINT DEFAULT NULL,
  math_input_type SMALLINT DEFAULT NULL,
  math_png BLOB DEFAULT NULL,
  PRIMARY KEY(math_inputhash)
);
