-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-drop-afl_ip.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX afl_ip_timestamp;

ALTER TABLE abuse_filter_log
  DROP afl_ip;
