-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-afh_actor.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  abuse_filter_history
ADD  afh_actor BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE  abuse_filter_history ALTER afh_user
SET  DEFAULT 0;
ALTER TABLE  abuse_filter_history ALTER afh_user_text
SET  DEFAULT '';
CREATE INDEX afh_actor ON abuse_filter_history (afh_actor);