-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE oathauth_types (
  oat_id SERIAL NOT NULL,
  oat_name TEXT NOT NULL,
  PRIMARY KEY(oat_id)
);

CREATE UNIQUE INDEX oat_name ON oathauth_types (oat_name);


CREATE TABLE oathauth_devices (
  oad_id SERIAL NOT NULL,
  oad_user INT NOT NULL,
  oad_type INT NOT NULL,
  oad_name TEXT DEFAULT NULL,
  oad_created TIMESTAMPTZ DEFAULT NULL,
  oad_data TEXT DEFAULT NULL,
  PRIMARY KEY(oad_id)
);

CREATE INDEX oad_user ON oathauth_devices (oad_user);


CREATE TABLE oathauth_user_handles (
  oah_user INT NOT NULL,
  oah_handle TEXT DEFAULT NULL,
  PRIMARY KEY(oah_user)
);

CREATE UNIQUE INDEX oah_handle ON oathauth_user_handles (oah_handle);
