-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/cuci_temp_edit.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cuci_temp_edit (
  cite_ip_hex VARBINARY(255) NOT NULL,
  cite_ciwm_id SMALLINT UNSIGNED NOT NULL,
  cite_timestamp BINARY(14) NOT NULL,
  INDEX cite_timestamp (cite_timestamp),
  INDEX cite_ip_hex_timestamp (cite_ip_hex, cite_timestamp),
  PRIMARY KEY(cite_ip_hex, cite_ciwm_id)
) /*$wgDBTableOptions*/;
