-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/cuci_wiki_map.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cuci_wiki_map (
  ciwm_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
  ciwm_wiki VARBINARY(255) NOT NULL,
  UNIQUE INDEX ciwm_wiki (ciwm_wiki),
  PRIMARY KEY(ciwm_id)
) /*$wgDBTableOptions*/;
