-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case-drop-sic_created_timestamp-indexes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX sic_status_created_timestamp_id ON /*_*/cusi_case;

DROP INDEX sic_created_timestamp_id ON /*_*/cusi_case;
