-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case-add-sic_updated_timestamp.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/cusi_case
  ADD sic_updated_timestamp BINARY(14) DEFAULT NULL;

CREATE UNIQUE INDEX sic_status_updated_timestamp_id ON /*_*/cusi_case (
  sic_status, sic_updated_timestamp,
  sic_id
);

CREATE UNIQUE INDEX sic_updated_timestamp_id ON /*_*/cusi_case (sic_updated_timestamp, sic_id);
