-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case-modify-sic_url_identifier.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX sic_url_identifier ON /*_*/cusi_case;

ALTER TABLE /*_*/cusi_case
  CHANGE sic_url_identifier sic_url_identifier INT UNSIGNED NOT NULL;

CREATE UNIQUE INDEX sic_url_identifier ON /*_*/cusi_case (sic_url_identifier);
