-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cu_log_event-drop-cule_ip.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX cule_actor_ip_time ON /*_*/cu_log_event;

ALTER TABLE /*_*/cu_log_event
  DROP cule_ip;
