-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_case-def.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cusi_case (
  sic_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  sic_status TINYINT UNSIGNED DEFAULT 0 NOT NULL,
  sic_status_reason VARBINARY(255) DEFAULT '' NOT NULL,
  sic_created_timestamp BINARY(14) NOT NULL,
  UNIQUE INDEX sic_status_created_timestamp_id (
    sic_status, sic_created_timestamp,
    sic_id
  ),
  UNIQUE INDEX sic_created_timestamp_id (sic_created_timestamp, sic_id),
  PRIMARY KEY(sic_id)
) /*$wgDBTableOptions*/;
