-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: schema/abstractSchemaChanges/patch-cusi_signal-def.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cusi_signal (
  sis_sic_id INT UNSIGNED NOT NULL,
  sis_name VARBINARY(255) NOT NULL,
  sis_value VARBINARY(255) NOT NULL,
  INDEX sis_sic_id (sis_sic_id),
  PRIMARY KEY(sis_name, sis_value, sis_sic_id)
) /*$wgDBTableOptions*/;
