-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: abstractSchemaChanges/patch-linter-add-template-tag-fields.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  linter
ADD  linter_template TEXT DEFAULT '' NOT NULL;
ALTER TABLE  linter
ADD  linter_tag TEXT DEFAULT '' NOT NULL;
CREATE INDEX linter_cat_template ON linter (linter_cat, linter_template);
CREATE INDEX linter_cat_tag ON linter (linter_cat, linter_tag);