services:
  app:
    build: php
    working_dir: /app
    environment:
      - HOME=/tmp
    user: "${UID}:${GID}"
    userns_mode: host
    volumes:
      - ../:/app
    tmpfs:
      - /tmp
    depends_on:
      - mariadb

  nginx:
    image: nginxinc/nginx-unprivileged:stable-alpine-slim
    ports:
      - "${PORT}:8080"
    volumes:
      - ../:/app:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    tmpfs:
      - /tmp
    depends_on:
      - app

  mariadb:
    image: mariadb:11
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    tmpfs:
      - /tmp
