<?php
/**
 * @license GPL-2.0-or-later
 */

namespace MediaWiki\Extension\OATHAuth\Auth;

use MediaWiki\Auth\AbstractSecondaryAuthenticationProvider;
use MediaWiki\Auth\AuthenticationRequest;
use MediaWiki\Auth\AuthenticationResponse;
use MediaWiki\Auth\AuthManager;
use MediaWiki\Extension\OATHAuth\Module\TOTP;
use MediaWiki\Extension\OATHAuth\OATHAuthLogger;
use MediaWiki\Extension\OATHAuth\OATHUserRepository;
use MediaWiki\Message\Message;

/**
 * AuthManager secondary authentication provider for TOTP second-factor authentication.
 *
 * After a successful primary authentication, requests a time-based one-time password
 * (typically generated by a mobile app such as Google Authenticator) from the user.
 *
 * @see AuthManager
 * @see https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm
 */
class TOTPSecondaryAuthenticationProvider extends AbstractSecondaryAuthenticationProvider {
	public function __construct(
		private readonly TOTP $module,
		private readonly OATHUserRepository $userRepository,
		private readonly OATHAuthLogger $oathLogger,
	) {
	}

	/** @inheritDoc */
	public function getAuthenticationRequests( $action, array $options ) {
		// don't ask for anything initially, so the second factor is on a separate screen
		return [];
	}

	/**
	 * If the user has enabled two-factor authentication, request a second factor.
	 *
	 * @inheritDoc
	 */
	public function beginSecondaryAuthentication( $user, array $reqs ) {
		$authUser = $this->userRepository->findByUser( $user );

		if ( !$this->module->isEnabled( $authUser ) ) {
			return AuthenticationResponse::newAbstain();
		}

		return AuthenticationResponse::newUI( [ new TOTPAuthenticationRequest() ] );
	}

	/** @inheritDoc */
	public function continueSecondaryAuthentication( $user, array $reqs ) {
		/** @var TOTPAuthenticationRequest $request */
		$request = AuthenticationRequest::getRequestByClass( $reqs, TOTPAuthenticationRequest::class );
		if ( !$request ) {
			return AuthenticationResponse::newUI( [ new TOTPAuthenticationRequest() ],
				wfMessage( 'oathauth-login-failed' ), 'error' );
		}

		// Check for (and increment) rate limiter before doing the auth
		if ( $user->pingLimiter( 'badoath' ) ) {
			return AuthenticationResponse::newUI(
				[ new TOTPAuthenticationRequest() ],
				new Message( 'oathauth-throttled' ),
				'error'
			);
		}

		$authUser = $this->userRepository->findByUser( $user );
		$token = $request->OATHToken;

		if ( $this->module->verify( $authUser, [ 'token' => $token ] ) ) {
			return AuthenticationResponse::newPass();
		}

		$this->logger->info( 'OATHAuth user {user} failed OTP token/recovery code from {clientip}', [
			'user'     => $user->getName(),
			'clientip' => $user->getRequest()->getIP(),
		] );

		$this->oathLogger->logFailedVerification( $user );

		return AuthenticationResponse::newUI(
			[ new TOTPAuthenticationRequest() ],
			wfMessage( 'oathauth-login-failed' ),
			'error'
		);
	}

	/** @inheritDoc */
	public function beginSecondaryAccountCreation( $user, $creator, array $reqs ) {
		return AuthenticationResponse::newAbstain();
	}
}
