-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/cu_useragent.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cu_useragent (
  cuua_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cuua_text BLOB NOT NULL
);

CREATE INDEX cuua_text ON /*_*/cu_useragent (cuua_text);
