-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/cuci_wiki_map.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cuci_wiki_map (
  ciwm_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ciwm_wiki BLOB NOT NULL
);

CREATE UNIQUE INDEX ciwm_wiki ON /*_*/cuci_wiki_map (ciwm_wiki);
