-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/tables-virtual-checkuser.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cusi_case (
  sic_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  sic_url_identifier INTEGER UNSIGNED NOT NULL,
  sic_status SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  sic_status_reason BLOB DEFAULT '' NOT NULL,
  sic_status_changed_by INTEGER UNSIGNED DEFAULT NULL,
  sic_created_timestamp BLOB NOT NULL,
  sic_updated_timestamp BLOB NOT NULL
);

CREATE UNIQUE INDEX sic_status_updated_timestamp_id ON /*_*/cusi_case (
  sic_status, sic_updated_timestamp,
  sic_id
);

CREATE UNIQUE INDEX sic_updated_timestamp_id ON /*_*/cusi_case (sic_updated_timestamp, sic_id);

CREATE UNIQUE INDEX sic_url_identifier ON /*_*/cusi_case (sic_url_identifier);

CREATE INDEX sic_status_changed_by_updated_timestamp_id ON /*_*/cusi_case (
  sic_status_changed_by, sic_updated_timestamp,
  sic_id
);


CREATE TABLE /*_*/cusi_user (
  siu_user_id INTEGER UNSIGNED NOT NULL,
  siu_sic_id INTEGER UNSIGNED NOT NULL,
  siu_info INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(siu_sic_id, siu_user_id)
);

CREATE INDEX siu_user_id ON /*_*/cusi_user (siu_user_id);


CREATE TABLE /*_*/cusi_signal (
  sis_sic_id INTEGER UNSIGNED NOT NULL,
  sis_name BLOB NOT NULL,
  sis_value BLOB NOT NULL,
  sis_trigger_id BIGINT UNSIGNED DEFAULT 0 NOT NULL,
  sis_trigger_type SMALLINT DEFAULT 0 NOT NULL,
  PRIMARY KEY(
    sis_name, sis_value, sis_sic_id, sis_trigger_id,
    sis_trigger_type
  )
);

CREATE INDEX sis_sic_id ON /*_*/cusi_signal (sis_sic_id);
