-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE loginnotify_seen_net (
  lsn_id SERIAL NOT NULL,
  lsn_time_bucket SMALLINT NOT NULL,
  lsn_user INT NOT NULL,
  lsn_subnet BIGINT NOT NULL,
  PRIMARY KEY(lsn_id)
);

CREATE UNIQUE INDEX loginnotify_seen_net_user ON loginnotify_seen_net (
  lsn_user, lsn_subnet, lsn_time_bucket
);
