-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/discussiontools_subscription.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/discussiontools_subscription (
  sub_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  sub_item VARBINARY(255) NOT NULL,
  sub_namespace INT DEFAULT 0 NOT NULL,
  sub_title VARBINARY(255) NOT NULL,
  sub_section VARBINARY(255) NOT NULL,
  sub_state INT DEFAULT 1 NOT NULL,
  sub_user INT UNSIGNED NOT NULL,
  sub_created BINARY(14) NOT NULL,
  sub_notified BINARY(14) DEFAULT NULL,
  UNIQUE INDEX discussiontools_subscription_itemuser (sub_item, sub_user),
  INDEX discussiontools_subscription_user (sub_user),
  PRIMARY KEY(sub_id)
) /*$wgDBTableOptions*/;
