-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-drop-afh_user.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX afh_user ON  /*_*/abuse_filter_history;
DROP  INDEX afh_user_text ON  /*_*/abuse_filter_history;
ALTER TABLE  /*_*/abuse_filter_history
DROP  afh_user,
DROP  afh_user_text,
CHANGE  afh_actor afh_actor BIGINT UNSIGNED NOT NULL;