-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-remove-default-afl_ip_hex.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/abuse_filter_log
  CHANGE afl_ip_hex afl_ip_hex VARCHAR(255) NOT NULL;
