-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-index-afl_var_dump_timestamp.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX afl_var_dump_timestamp ON /*_*/abuse_filter_log (
  afl_var_dump(4),
  afl_timestamp
);
