-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-afl_ip_hex.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/abuse_filter_log
  ADD afl_ip_hex VARCHAR(255) DEFAULT '' NOT NULL;

CREATE INDEX afl_ip_hex_timestamp ON /*_*/abuse_filter_log (afl_ip_hex, afl_timestamp);
