-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db_patches/abstractSchemaChanges/patch-add-af_actor.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/abuse_filter
ADD  af_actor BIGINT UNSIGNED DEFAULT 0 NOT NULL,
CHANGE  af_user af_user BIGINT UNSIGNED DEFAULT 0 NOT NULL,
CHANGE  af_user_text af_user_text VARBINARY(255) DEFAULT '' NOT NULL;
CREATE INDEX af_actor ON  /*_*/abuse_filter (af_actor);