-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-add-oathauth_user_handles.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/oathauth_user_handles (
  oah_user INT UNSIGNED NOT NULL,
  oah_handle VARBINARY(88) DEFAULT NULL,
  UNIQUE INDEX oah_handle (oah_handle),
  PRIMARY KEY(oah_user)
) /*$wgDBTableOptions*/;
