<?php

/**
 * Generated by Peggy 5.0.6 with PHPeggy plugin 3.0.0
 *
 * https://peggyjs.org/
 * https://github.com/marcelbolten/phpeggy
 */

declare(strict_types=1);

namespace MediaWiki\Extension\Math\WikiTexVC;

/* BEGIN Utility functions */
/* chr_unicode - get unicode character from its char code */
if (!\function_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\chr_unicode")) {
    /** @param float|int $code */
    function chr_unicode(
        $code
    ): string {
        return \html_entity_decode("&#" . (int) $code . ";", ENT_QUOTES, "UTF-8");
    }
}

/* ord_unicode - get unicode char code from string */
if (!\function_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\ord_unicode")) {
    function ord_unicode(
        string $character
    ): int {
        if (\strlen($character) === 1) {
            return \ord($character);
        }
        $json = \json_encode($character, \JSON_THROW_ON_ERROR);
        $utf16_1 = (int) \hexdec(\substr($json, 3, 4));
        if (substr($json, 7, 2) === "\u") {
            $utf16_2 = (int) \hexdec(\substr($json, 9, 4));
            return 0x10000 + (($utf16_1 & 0x3ff) << 10) + ($utf16_2 & 0x3ff);
        }

        return $utf16_1;
    }
}
/* END Utility functions */

/* Syntax error exception */
if (!\class_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\SyntaxError", false)) {
    class SyntaxError extends \Exception
    {
        public string $name = "SyntaxError";

        /**
         * @param pegExpectation[]|null $expected
         */
        public function __construct(
            ?string $message,
            public ?array $expected,
            public string $found,
            public int $grammarOffset,
            public int $grammarLine,
            public int $grammarColumn,
            public pegLocation $location
        ) {
            parent::__construct($message ?? "", 0);
        }

        /**
         * @param array<int, array<string, string>> $sources
         */
        public function format(
            array $sources
        ): string {
            $str = $this->name . ": " . $this->message;
            if (!empty($this->location->source)) {
                $src = null;
                for ($k = 0; $k < \count($sources); $k++) {
                    if ($sources[$k]["source"] === $this->location->source) {
                        $src = \preg_split("/\r\n|\n|\r/", $sources[$k]["text"]);
                        break;
                    }
                }
                $start = $this->location->start;
                $loc = $this->location->source . ":" . $start->line . ":" . $start->column;
                if ($src) {
                    $end = $this->location->end;
                    $filler = $this->peg_padEnd("", $start->line !== 0 ? (int) \floor(\log10($start->line) + 1.0) : 1);
                    $line = $src[$start->line - 1];
                    $last = $start->line === $end->line ? $end->column : \strlen($line) + 1;
                    $hatLen = ($last - $start->column) ?: 1;
                    $str .= "\n --> " . $loc . "\n"
                        . $filler . " |\n"
                        . $start->line . " | " . $line . "\n"
                        . $filler . " | " . $this->peg_padEnd("", $start->column - 1)
                        . $this->peg_padEnd("", $hatLen, "^");
                } else {
                    $str .= "\n at " . $loc;
                }
            }
            return $str;
        }

        private function peg_padEnd(
            string $str,
            int $targetLength,
            string $padString = " "
        ): string {
            if (\strlen($str) > $targetLength) {
                return $str;
            }
            $targetLength -= \strlen($str);
            $padString .= \str_repeat($padString, $targetLength);
            return $str . \substr($padString, 0, $targetLength);
        }
    }
}

if (!\class_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\pegExpectation", false)) {
    class pegExpectation
    {
        public function __construct(
            public ?string $type = null,
            public ?string $description = null,
            public ?string $value = null,
            public ?string $ignoreCase = null,
            public ?string $unicode = null
        ) {
        }
    }
}

if (!\class_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\pegCacheItem", false)) {
    class pegCacheItem
    {
        public function __construct(
            public int $nextPos,
            public mixed $result
        ) {
        }
    }
}

if (!\class_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\pegCachedPosDetails", false)) {
    class pegCachedPosDetails
    {
        public function __construct(
            public int $line = 1,
            public int $column = 1,
            public bool $seenCR = false
        ) {
        }
    }
}

if (!\class_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\pegLocation", false)) {
    class pegLocation
    {
        public function __construct(
            public string $source,
            public pegPosition $start,
            public pegPosition $end
        ) {
        }
    }
}

if (!\class_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\pegPosition", false)) {
    class pegPosition
    {
        public function __construct(
            public int $offset,
            public int $line,
            public int $column
        ) {
        }
    }
}

if (!\class_exists("MediaWiki\\Extension\\Math\\WikiTexVC\\pegRange", false)) {
    class pegRange
    {
        public function __construct(
            public string $source,
            public int $start,
            public int $end
        ) {
        }
    }
}

class ParserIntent
{
    /** @var pegCacheItem[] */
    public array $peg_cache = [];

    private int $peg_currPos = 0;
    private int $peg_reportedPos = 0;
    private int $peg_cachedPos = 0;
    private pegCachedPosDetails $peg_cachedPosDetails;
    private int $peg_maxFailPos = 0;
    /** @var pegExpectation[] $peg_maxFailExpected */
    private array $peg_maxFailExpected = [];
    private int $peg_silentFails = 0;
    /** @var string[] $input */
    private array $input = [];
    /** @var array<string, mixed> $options */
    private array $options = [];
    private int $input_length = 0;
    private \stdClass $peg_FAILED;
    private string $peg_source = "";

    private string $peg_l0 = "-";
    private string $peg_l1 = ".";
    private string $peg_l2 = "\$";
    private string $peg_l3 = ":";
    private string $peg_l4 = "common";
    private string $peg_l5 = "structure";
    private string $peg_l6 = "chemistry";
    private string $peg_l7 = "matrix";
    private string $peg_l8 = "equations";
    private string $peg_l9 = "chemical-element";
    private string $peg_l10 = "chemical-formula";
    private string $peg_l11 = "chemical-equation";
    private string $peg_l12 = "(";
    private string $peg_l13 = ")";
    private string $peg_l14 = ",";
    private string $peg_l15 = "prefix";
    private string $peg_l16 = "infix";
    private string $peg_l17 = "postfix";
    private string $peg_l18 = "function";
    private string $peg_l19 = "silent";
    private string $peg_l20 = "decimal-comma";
    private string $peg_l21 = "thousands-comma";
    private string $peg_l22 = " ";
    private string $peg_c0 = "/^[0-9]/";
    private string $peg_c1 = "/^[:@]/";
    private string $peg_c2 = "/^[a-zA-Z_]/";
    private string $peg_c3 = "/^[a-zA-Z0-9._-]/";
    private pegExpectation $peg_e0;
    private pegExpectation $peg_e1;
    private pegExpectation $peg_e2;
    private pegExpectation $peg_e3;
    private pegExpectation $peg_e4;
    private pegExpectation $peg_e5;
    private pegExpectation $peg_e6;
    private pegExpectation $peg_e7;
    private pegExpectation $peg_e8;
    private pegExpectation $peg_e9;
    private pegExpectation $peg_e10;
    private pegExpectation $peg_e11;
    private pegExpectation $peg_e12;
    private pegExpectation $peg_e13;
    private pegExpectation $peg_e14;
    private pegExpectation $peg_e15;
    private pegExpectation $peg_e16;
    private pegExpectation $peg_e17;
    private pegExpectation $peg_e18;
    private pegExpectation $peg_e19;
    private pegExpectation $peg_e20;
    private pegExpectation $peg_e21;
    private pegExpectation $peg_e22;
    private pegExpectation $peg_e23;
    private pegExpectation $peg_e24;
    private pegExpectation $peg_e25;
    private pegExpectation $peg_e26;

    public function __construct()
    {
        $this->peg_FAILED = new \stdClass();
        $this->peg_cachedPosDetails = new pegCachedPosDetails();
        $this->peg_e0 = new pegExpectation("literal", "\"-\"", "-", "false");
        $this->peg_e1 = new pegExpectation("literal", "\".\"", ".", "false");
        $this->peg_e2 = new pegExpectation("class", "[0-9]", "[0-9]", "false", "false");
        $this->peg_e3 = new pegExpectation("literal", "\"\\\$\"", "\$", "false");
        $this->peg_e4 = new pegExpectation("literal", "\":\"", ":", "false");
        $this->peg_e5 = new pegExpectation("literal", "\"common\"", "common", "false");
        $this->peg_e6 = new pegExpectation("literal", "\"structure\"", "structure", "false");
        $this->peg_e7 = new pegExpectation("literal", "\"chemistry\"", "chemistry", "false");
        $this->peg_e8 = new pegExpectation("literal", "\"matrix\"", "matrix", "false");
        $this->peg_e9 = new pegExpectation("literal", "\"equations\"", "equations", "false");
        $this->peg_e10 = new pegExpectation("literal", "\"chemical-element\"", "chemical-element", "false");
        $this->peg_e11 = new pegExpectation("literal", "\"chemical-formula\"", "chemical-formula", "false");
        $this->peg_e12 = new pegExpectation("literal", "\"chemical-equation\"", "chemical-equation", "false");
        $this->peg_e13 = new pegExpectation("literal", "\"(\"", "(", "false");
        $this->peg_e14 = new pegExpectation("literal", "\")\"", ")", "false");
        $this->peg_e15 = new pegExpectation("literal", "\",\"", ",", "false");
        $this->peg_e16 = new pegExpectation("class", "[:@]", "[:@]", "false", "false");
        $this->peg_e17 = new pegExpectation("literal", "\"prefix\"", "prefix", "false");
        $this->peg_e18 = new pegExpectation("literal", "\"infix\"", "infix", "false");
        $this->peg_e19 = new pegExpectation("literal", "\"postfix\"", "postfix", "false");
        $this->peg_e20 = new pegExpectation("literal", "\"function\"", "function", "false");
        $this->peg_e21 = new pegExpectation("literal", "\"silent\"", "silent", "false");
        $this->peg_e22 = new pegExpectation("literal", "\"decimal-comma\"", "decimal-comma", "false");
        $this->peg_e23 = new pegExpectation("literal", "\"thousands-comma\"", "thousands-comma", "false");
        $this->peg_e24 = new pegExpectation("class", "[a-zA-Z_]", "[a-zA-Z_]", "false", "false");
        $this->peg_e25 = new pegExpectation("class", "[a-zA-Z0-9._-]", "[a-zA-Z0-9._-]", "false", "false");
        $this->peg_e26 = new pegExpectation("literal", "\" \"", " ", "false");
    }

    /**
     * @param string|string[] $input
     * @param mixed[] $args
     * @throws \Exception
     * @throws SyntaxError
     */
    public function parse(
        $input,
        array ...$args
    ): mixed {
        $this->peg_cleanup_state();
        $this->options = $args[0] ?? [];
        if (\is_array($input)) {
            $this->input = $input;
        } else {
            \preg_match_all("/./us", $input, $match);
            $this->input = $match[0];
        }
        $this->input_length = \count($this->input);
        $this->peg_source = $this->options["grammarSource"] ?? "";

        $old_regex_encoding = (string) \mb_regex_encoding();
        \mb_regex_encoding("UTF-8");

        if (method_exists($this, 'initialize')) {
            $this->initialize();
        }

        $peg_startRuleFunctions = ["start" => [$this, "peg_parse_start"]];
        $peg_startRuleFunction = [$this, "peg_parse_start"];
        if (isset($this->options["startRule"])) {
            if (!isset($peg_startRuleFunctions[$this->options["startRule"]])) {
                throw new \Exception("Can't start parsing from rule \"" . $this->options["startRule"] . "\".");
            }

            $peg_startRuleFunction = $peg_startRuleFunctions[$this->options["startRule"]];
        }

        /* @var mixed $peg_result */
        $peg_result = \call_user_func($peg_startRuleFunction);

        $this->peg_cache = [];

        \mb_regex_encoding($old_regex_encoding);

        if ($peg_result !== $this->peg_FAILED && $this->peg_currPos === $this->input_length) {
            $this->peg_cleanup_state();
            return $peg_result;
        }

        if ($peg_result !== $this->peg_FAILED && $this->peg_currPos < $this->input_length) {
            $this->peg_fail(new pegExpectation("end", "end of input"));
        }

        $exception = $this->peg_buildException(null, $this->peg_maxFailExpected, $this->peg_maxFailPos);
        $this->peg_cleanup_state();
        throw $exception;
    }

    private function peg_cleanup_state(): void
    {
        $this->peg_cache = [];
        $this->peg_currPos = 0;
        $this->peg_reportedPos = 0;
        $this->peg_cachedPos = 0;
        $this->peg_cachedPosDetails = new pegCachedPosDetails();
        $this->peg_maxFailPos = 0;
        $this->peg_maxFailExpected = [];
        $this->peg_silentFails = 0;
        $this->input = [];
        $this->input_length = 0;
        $this->options = [];
        $this->peg_source = "";
    }

    private function input_substr(
        int $start,
        int $length
    ): string {
        if ($length === 1 && $start < $this->input_length) {
            return $this->input[$start];
        }
        $substr = "";
        $max = \min($start + $length, $this->input_length);
        for ($i = $start; $i < $max; $i++) {
            $substr .= $this->input[$i];
        }
        return $substr;
    }

    private function text(): string
    {
        return $this->input_substr($this->peg_reportedPos, $this->peg_currPos - $this->peg_reportedPos);
    }

    private function offset(): int
    {
        return $this->peg_reportedPos;
    }

    private function range(): pegRange
    {
        return new pegRange($this->peg_source, $this->peg_reportedPos, $this->peg_currPos);
    }

    private function location(
        bool $fail = false
    ): pegLocation {
        $start = $this->peg_reportedPos;
        $end = $this->peg_currPos;
        if ($fail) {
            $start = $this->peg_maxFailPos;
            $end = $this->peg_maxFailPos + ($this->peg_maxFailPos < \count($this->input) ? 1 : 0);
        }
        $compute_pd_start = clone $this->peg_computePosDetails($start);
        $compute_pd_end = clone $this->peg_computePosDetails($end);

        return new pegLocation(
            $this->peg_source,
            new pegPosition($start, $compute_pd_start->line, $compute_pd_start->column),
            new pegPosition($end, $compute_pd_end->line, $compute_pd_end->column),
        );
    }

    private function line(): int
    {
        return $this->peg_computePosDetails($this->peg_reportedPos)->line;
    }

    private function column(): int
    {
        return $this->peg_computePosDetails($this->peg_reportedPos)->column;
    }

    /**
     * @throws SyntaxError
     */
    private function expected(
        string $description,
        ?int $where = null
    ): void {
        throw $this->peg_buildException(
            null,
            [new pegExpectation("other", $description)],
            $where ?? $this->peg_reportedPos
        );
    }

    /**
     * @throws SyntaxError
     */
    private function error(
        string $message,
        ?int $where = null
    ): void {
        throw $this->peg_buildException(
            $message,
            null,
            $where ?? $this->peg_reportedPos,
        );
    }

    private function peg_advancePos(
        pegCachedPosDetails $details,
        int $startPos,
        int $endPos
    ): void {
        for ($p = $startPos; $p < $endPos; $p++) {
            $ch = $this->input_substr($p, 1);
            if ($ch === "\n") {
                if (!$details->seenCR) {
                    $details->line++;
                }
                $details->column = 1;
                $details->seenCR = false;
            } elseif ($ch === "\r" || $ch === "\u2028" || $ch === "\u2029") {
                $details->line++;
                $details->column = 1;
                $details->seenCR = true;
            } else {
                $details->column++;
                $details->seenCR = false;
            }
        }
    }

    private function peg_computePosDetails(
        int $pos
    ): pegCachedPosDetails {
        if ($this->peg_cachedPos !== $pos) {
            if ($this->peg_cachedPos > $pos) {
                $this->peg_cachedPos = 0;
                $this->peg_cachedPosDetails = new pegCachedPosDetails();
            }
            $this->peg_advancePos($this->peg_cachedPosDetails, $this->peg_cachedPos, $pos);
            $this->peg_cachedPos = $pos;
        }

        return $this->peg_cachedPosDetails;
    }

    private function peg_fail(
        pegExpectation $expected
    ): void {
        if ($this->peg_currPos < $this->peg_maxFailPos) {
            return;
        }

        if ($this->peg_currPos > $this->peg_maxFailPos) {
            $this->peg_maxFailPos = $this->peg_currPos;
            $this->peg_maxFailExpected = [];
        }

        $this->peg_maxFailExpected[] = $expected;
    }

    private function peg_buildException_expectedComparator(
        pegExpectation $a,
        pegExpectation $b
    ): int {
        return $a->description <=> $b->description;
    }

    /** @param pegExpectation[]|null $expected */
    private function peg_buildException(
        ?string $message,
        ?array $expected,
        int $pos
    ): SyntaxError {
        $posDetails = $this->peg_computePosDetails($pos);
        $found = $pos < $this->input_length ? $this->input[$pos] : null;

        if ($expected !== null) {
            \usort($expected, [$this, "peg_buildException_expectedComparator"]);
            $i = 1;
            while ($i < \count($expected)) {
                if ($expected[$i - 1] === $expected[$i]) {
                    \array_splice($expected, $i, 1);
                } else {
                    $i++;
                }
            }
        }

        if ($message === null && $expected !== null) {
            $expectedDescs = \array_fill(0, \count($expected), null);

            for ($i = 0; $i < \count($expected); $i++) {
                $expectedDescs[$i] = $expected[$i]->description;
            }

            $expectedDesc = \count($expected) > 1
                ? \implode(", ", \array_slice($expectedDescs, 0, -1))
                    . " or "
                    . ($expectedDescs[\count($expected) - 1] ?? "")
                : $expectedDescs[0] ?? "";

            $foundDesc = $found === null ? "end of input" : \json_encode($found, JSON_THROW_ON_ERROR);

            $message = \sprintf("Expected %s but %s found.", $expectedDesc, $foundDesc);
        }

        return new SyntaxError(
            $message,
            $expected,
            $found ?? "",
            $pos,
            $posDetails->line,
            $posDetails->column,
            $this->location(true)
        );
    }

    private function peg_f0(
    ): mixed {
        return $this->text();
    }

    private function peg_f1(
        mixed $sign,
        mixed $intPart,
        mixed $fracPart,
        mixed $hint,
    ): mixed {
        $intPartS = implode($intPart ?? []);
                $fracPartS = implode($fracPart[1] ?? []);
                $value = $sign ?? "";
                $value .= $intPartS;
                $value .= isset($fracPart) ? ("." . $fracPartS ) : "";
                return ["type" => "number", "value" => $value, "hint"=>$hint];
    }

    private function peg_f2(
    ): mixed {
        return substr($this->text(),1);
    }

    private function peg_f3(
    ): mixed {
        return substr($this->text(),1);
    }

    private function peg_f4(
        mixed $intent,
        mixed $hint,
        mixed $args,
    ): mixed {
        $argsF = [];
        foreach ($args as $arg) {
           $argsF[] = $arg[2];
        }
       $returnObj =  [
             "type" => "application",
             "intent" => $intent,
             "hint" => isset($hint) ? $hint : null,
             "arguments" => $argsF
         ];
       return $returnObj;
    }

    private function peg_f5(
        mixed $first,
        mixed $rest,
    ): mixed {
        $args = [$first];
          foreach ($rest as $arg) {
              $args[] = $arg[2];
          }
          return $args;
    }

    private function peg_f6(
        mixed $hintType,
    ): mixed {
        return $hintType;
    }

    private function peg_f7(
    ): mixed {
        return $this->text();
    }

    private function peg_f8(
    ): mixed {
        return " ";
    }

    private function peg_parse_start(): mixed
    {
        $key = $this->peg_currPos * 13 + 0;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_parse_application();
        if ($s0 === $this->peg_FAILED) {
            $s0 = $this->peg_parse_intent();
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_intent(): mixed
    {
        $key = $this->peg_currPos * 13 + 1;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_parse_concept_or_literal();
        if ($s0 === $this->peg_FAILED) {
            $s0 = $this->peg_parse_number();
            if ($s0 === $this->peg_FAILED) {
                $s0 = $this->peg_parse_reference();
                if ($s0 === $this->peg_FAILED) {
                    $s0 = $this->peg_parse_structure();
                }
            }
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_concept_or_literal(): mixed
    {
        $key = $this->peg_currPos * 13 + 2;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        $s1 = $this->peg_parse_NCName();
        if ($s1 !== $this->peg_FAILED) {
            $this->peg_reportedPos = $s0;
            $s1 = $this->peg_f0();
        }
        $s0 = $s1;

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_number(): mixed
    {
        $key = $this->peg_currPos * 13 + 3;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l0) {
            $s1 = $this->peg_l0;
            $this->peg_currPos++;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e0);
            }
        }
        if ($s1 === $this->peg_FAILED) {
            $s1 = null;
        }
        $s2 = $this->peg_parse_digits();
        if ($s2 !== $this->peg_FAILED) {
            $s3 = $this->peg_currPos;
            if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l1) {
                $s4 = $this->peg_l1;
                $this->peg_currPos++;
            } else {
                $s4 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e1);
                }
            }
            if ($s4 !== $this->peg_FAILED) {
                $s5 = $this->peg_parse_digits();
                if ($s5 !== $this->peg_FAILED) {
                    $s4 = [$s4, $s5];
                    $s3 = $s4;
                } else {
                    $this->peg_currPos = $s3;
                    $s3 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s3;
                $s3 = $this->peg_FAILED;
            }
            if ($s3 === $this->peg_FAILED) {
                $s3 = null;
            }
            $s4 = $this->peg_parse_hint();
            if ($s4 === $this->peg_FAILED) {
                $s4 = null;
            }
            $this->peg_reportedPos = $s0;
            $s0 = $this->peg_f1($s1, $s2, $s3, $s4);
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_digits(): mixed
    {
        $key = $this->peg_currPos * 13 + 4;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = [];
        $s1 = $this->peg_parse_digit();
        if ($s1 !== $this->peg_FAILED) {
            while ($s1 !== $this->peg_FAILED) {
                $s0[] = $s1;
                $s1 = $this->peg_parse_digit();
            }
        } else {
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_digit(): mixed
    {
        $key = $this->peg_currPos * 13 + 5;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->input_substr($this->peg_currPos, 1);
        if (\preg_match($this->peg_c0, $s0)) {
            $this->peg_currPos++;
        } else {
            $s0 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e2);
            }
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_reference(): mixed
    {
        $key = $this->peg_currPos * 13 + 6;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l2) {
            $s1 = $this->peg_l2;
            $this->peg_currPos++;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e3);
            }
        }
        if ($s1 !== $this->peg_FAILED) {
            $s2 = $this->peg_parse_NCName();
            if ($s2 !== $this->peg_FAILED) {
                $this->peg_reportedPos = $s0;
                $s0 = $this->peg_f2();
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_structure(): mixed
    {
        $key = $this->peg_currPos * 13 + 7;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l3) {
            $s1 = $this->peg_l3;
            $this->peg_currPos++;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e4);
            }
        }
        if ($s1 !== $this->peg_FAILED) {
            if ($this->input_substr($this->peg_currPos, 6) === $this->peg_l4) {
                $s2 = $this->peg_l4;
                $this->peg_currPos += 6;
            } else {
                $s2 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e5);
                }
            }
            if ($s2 === $this->peg_FAILED) {
                if ($this->input_substr($this->peg_currPos, 9) === $this->peg_l5) {
                    $s2 = $this->peg_l5;
                    $this->peg_currPos += 9;
                } else {
                    $s2 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e6);
                    }
                }
                if ($s2 === $this->peg_FAILED) {
                    if ($this->input_substr($this->peg_currPos, 9) === $this->peg_l6) {
                        $s2 = $this->peg_l6;
                        $this->peg_currPos += 9;
                    } else {
                        $s2 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e7);
                        }
                    }
                    if ($s2 === $this->peg_FAILED) {
                        if ($this->input_substr($this->peg_currPos, 6) === $this->peg_l7) {
                            $s2 = $this->peg_l7;
                            $this->peg_currPos += 6;
                        } else {
                            $s2 = $this->peg_FAILED;
                            if ($this->peg_silentFails === 0) {
                                $this->peg_fail($this->peg_e8);
                            }
                        }
                        if ($s2 === $this->peg_FAILED) {
                            if ($this->input_substr($this->peg_currPos, 9) === $this->peg_l8) {
                                $s2 = $this->peg_l8;
                                $this->peg_currPos += 9;
                            } else {
                                $s2 = $this->peg_FAILED;
                                if ($this->peg_silentFails === 0) {
                                    $this->peg_fail($this->peg_e9);
                                }
                            }
                            if ($s2 === $this->peg_FAILED) {
                                if ($this->input_substr($this->peg_currPos, 16) === $this->peg_l9) {
                                    $s2 = $this->peg_l9;
                                    $this->peg_currPos += 16;
                                } else {
                                    $s2 = $this->peg_FAILED;
                                    if ($this->peg_silentFails === 0) {
                                        $this->peg_fail($this->peg_e10);
                                    }
                                }
                                if ($s2 === $this->peg_FAILED) {
                                    if ($this->input_substr($this->peg_currPos, 16) === $this->peg_l10) {
                                        $s2 = $this->peg_l10;
                                        $this->peg_currPos += 16;
                                    } else {
                                        $s2 = $this->peg_FAILED;
                                        if ($this->peg_silentFails === 0) {
                                            $this->peg_fail($this->peg_e11);
                                        }
                                    }
                                    if ($s2 === $this->peg_FAILED) {
                                        if ($this->input_substr($this->peg_currPos, 17) === $this->peg_l11) {
                                            $s2 = $this->peg_l11;
                                            $this->peg_currPos += 17;
                                        } else {
                                            $s2 = $this->peg_FAILED;
                                            if ($this->peg_silentFails === 0) {
                                                $this->peg_fail($this->peg_e12);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if ($s2 !== $this->peg_FAILED) {
                $this->peg_reportedPos = $s0;
                $s0 = $this->peg_f3();
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_application(): mixed
    {
        $key = $this->peg_currPos * 13 + 8;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        $s1 = $this->peg_parse_intent();
        if ($s1 !== $this->peg_FAILED) {
            $s2 = $this->peg_parse_hint();
            if ($s2 === $this->peg_FAILED) {
                $s2 = null;
            }
            $s3 = [];
            $s4 = $this->peg_currPos;
            if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l12) {
                $s5 = $this->peg_l12;
                $this->peg_currPos++;
            } else {
                $s5 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e13);
                }
            }
            if ($s5 !== $this->peg_FAILED) {
                $s6 = $this->peg_parse_WS();
                if ($s6 === $this->peg_FAILED) {
                    $s6 = null;
                }
                $s7 = $this->peg_parse_intent_arguments();
                if ($s7 === $this->peg_FAILED) {
                    $s7 = null;
                }
                $s8 = $this->peg_parse_WS();
                if ($s8 === $this->peg_FAILED) {
                    $s8 = null;
                }
                if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l13) {
                    $s9 = $this->peg_l13;
                    $this->peg_currPos++;
                } else {
                    $s9 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e14);
                    }
                }
                if ($s9 !== $this->peg_FAILED) {
                    $s5 = [$s5, $s6, $s7, $s8, $s9];
                    $s4 = $s5;
                } else {
                    $this->peg_currPos = $s4;
                    $s4 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s4;
                $s4 = $this->peg_FAILED;
            }
            if ($s4 !== $this->peg_FAILED) {
                while ($s4 !== $this->peg_FAILED) {
                    $s3[] = $s4;
                    $s4 = $this->peg_currPos;
                    if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l12) {
                        $s5 = $this->peg_l12;
                        $this->peg_currPos++;
                    } else {
                        $s5 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e13);
                        }
                    }
                    if ($s5 !== $this->peg_FAILED) {
                        $s6 = $this->peg_parse_WS();
                        if ($s6 === $this->peg_FAILED) {
                            $s6 = null;
                        }
                        $s7 = $this->peg_parse_intent_arguments();
                        if ($s7 === $this->peg_FAILED) {
                            $s7 = null;
                        }
                        $s8 = $this->peg_parse_WS();
                        if ($s8 === $this->peg_FAILED) {
                            $s8 = null;
                        }
                        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l13) {
                            $s9 = $this->peg_l13;
                            $this->peg_currPos++;
                        } else {
                            $s9 = $this->peg_FAILED;
                            if ($this->peg_silentFails === 0) {
                                $this->peg_fail($this->peg_e14);
                            }
                        }
                        if ($s9 !== $this->peg_FAILED) {
                            $s5 = [$s5, $s6, $s7, $s8, $s9];
                            $s4 = $s5;
                        } else {
                            $this->peg_currPos = $s4;
                            $s4 = $this->peg_FAILED;
                        }
                    } else {
                        $this->peg_currPos = $s4;
                        $s4 = $this->peg_FAILED;
                    }
                }
            } else {
                $s3 = $this->peg_FAILED;
            }
            if ($s3 !== $this->peg_FAILED) {
                $this->peg_reportedPos = $s0;
                $s0 = $this->peg_f4($s1, $s2, $s3);
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_intent_arguments(): mixed
    {
        $key = $this->peg_currPos * 13 + 9;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        $s1 = $this->peg_parse_WS();
        if ($s1 === $this->peg_FAILED) {
            $s1 = null;
        }
        $s2 = $this->peg_parse_start();
        if ($s2 !== $this->peg_FAILED) {
            $s3 = $this->peg_parse_WS();
            if ($s3 === $this->peg_FAILED) {
                $s3 = null;
            }
            $s4 = [];
            $s5 = $this->peg_currPos;
            if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l14) {
                $s6 = $this->peg_l14;
                $this->peg_currPos++;
            } else {
                $s6 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e15);
                }
            }
            if ($s6 !== $this->peg_FAILED) {
                $s7 = $this->peg_parse_WS();
                if ($s7 === $this->peg_FAILED) {
                    $s7 = null;
                }
                $s8 = $this->peg_parse_start();
                if ($s8 !== $this->peg_FAILED) {
                    $s9 = $this->peg_parse_WS();
                    if ($s9 === $this->peg_FAILED) {
                        $s9 = null;
                    }
                    $s6 = [$s6, $s7, $s8, $s9];
                    $s5 = $s6;
                } else {
                    $this->peg_currPos = $s5;
                    $s5 = $this->peg_FAILED;
                }
            } else {
                $this->peg_currPos = $s5;
                $s5 = $this->peg_FAILED;
            }
            while ($s5 !== $this->peg_FAILED) {
                $s4[] = $s5;
                $s5 = $this->peg_currPos;
                if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l14) {
                    $s6 = $this->peg_l14;
                    $this->peg_currPos++;
                } else {
                    $s6 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e15);
                    }
                }
                if ($s6 !== $this->peg_FAILED) {
                    $s7 = $this->peg_parse_WS();
                    if ($s7 === $this->peg_FAILED) {
                        $s7 = null;
                    }
                    $s8 = $this->peg_parse_start();
                    if ($s8 !== $this->peg_FAILED) {
                        $s9 = $this->peg_parse_WS();
                        if ($s9 === $this->peg_FAILED) {
                            $s9 = null;
                        }
                        $s6 = [$s6, $s7, $s8, $s9];
                        $s5 = $s6;
                    } else {
                        $this->peg_currPos = $s5;
                        $s5 = $this->peg_FAILED;
                    }
                } else {
                    $this->peg_currPos = $s5;
                    $s5 = $this->peg_FAILED;
                }
            }
            $this->peg_reportedPos = $s0;
            $s0 = $this->peg_f5($s2, $s4);
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_hint(): mixed
    {
        $key = $this->peg_currPos * 13 + 10;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        $s1 = $this->input_substr($this->peg_currPos, 1);
        if (\preg_match($this->peg_c1, $s1)) {
            $this->peg_currPos++;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e16);
            }
        }
        if ($s1 !== $this->peg_FAILED) {
            if ($this->input_substr($this->peg_currPos, 6) === $this->peg_l15) {
                $s2 = $this->peg_l15;
                $this->peg_currPos += 6;
            } else {
                $s2 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e17);
                }
            }
            if ($s2 === $this->peg_FAILED) {
                if ($this->input_substr($this->peg_currPos, 5) === $this->peg_l16) {
                    $s2 = $this->peg_l16;
                    $this->peg_currPos += 5;
                } else {
                    $s2 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e18);
                    }
                }
                if ($s2 === $this->peg_FAILED) {
                    if ($this->input_substr($this->peg_currPos, 7) === $this->peg_l17) {
                        $s2 = $this->peg_l17;
                        $this->peg_currPos += 7;
                    } else {
                        $s2 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e19);
                        }
                    }
                    if ($s2 === $this->peg_FAILED) {
                        if ($this->input_substr($this->peg_currPos, 8) === $this->peg_l18) {
                            $s2 = $this->peg_l18;
                            $this->peg_currPos += 8;
                        } else {
                            $s2 = $this->peg_FAILED;
                            if ($this->peg_silentFails === 0) {
                                $this->peg_fail($this->peg_e20);
                            }
                        }
                        if ($s2 === $this->peg_FAILED) {
                            if ($this->input_substr($this->peg_currPos, 6) === $this->peg_l19) {
                                $s2 = $this->peg_l19;
                                $this->peg_currPos += 6;
                            } else {
                                $s2 = $this->peg_FAILED;
                                if ($this->peg_silentFails === 0) {
                                    $this->peg_fail($this->peg_e21);
                                }
                            }
                            if ($s2 === $this->peg_FAILED) {
                                if ($this->input_substr($this->peg_currPos, 13) === $this->peg_l20) {
                                    $s2 = $this->peg_l20;
                                    $this->peg_currPos += 13;
                                } else {
                                    $s2 = $this->peg_FAILED;
                                    if ($this->peg_silentFails === 0) {
                                        $this->peg_fail($this->peg_e22);
                                    }
                                }
                                if ($s2 === $this->peg_FAILED) {
                                    if ($this->input_substr($this->peg_currPos, 15) === $this->peg_l21) {
                                        $s2 = $this->peg_l21;
                                        $this->peg_currPos += 15;
                                    } else {
                                        $s2 = $this->peg_FAILED;
                                        if ($this->peg_silentFails === 0) {
                                            $this->peg_fail($this->peg_e23);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if ($s2 !== $this->peg_FAILED) {
                $this->peg_reportedPos = $s0;
                $s0 = $this->peg_f6($s2);
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_NCName(): mixed
    {
        $key = $this->peg_currPos * 13 + 11;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        $s1 = $this->peg_currPos;
        $this->peg_silentFails++;
        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l3) {
            $s2 = $this->peg_l3;
            $this->peg_currPos++;
        } else {
            $s2 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e4);
            }
        }
        $this->peg_silentFails--;
        if ($s2 === $this->peg_FAILED) {
            $s1 = null;
        } else {
            $this->peg_currPos = $s1;
            $s1 = $this->peg_FAILED;
        }
        if ($s1 !== $this->peg_FAILED) {
            $s2 = $this->input_substr($this->peg_currPos, 1);
            if (\preg_match($this->peg_c2, $s2)) {
                $this->peg_currPos++;
            } else {
                $s2 = $this->peg_FAILED;
                if ($this->peg_silentFails === 0) {
                    $this->peg_fail($this->peg_e24);
                }
            }
            if ($s2 !== $this->peg_FAILED) {
                $s3 = [];
                $s4 = $this->input_substr($this->peg_currPos, 1);
                if (\preg_match($this->peg_c3, $s4)) {
                    $this->peg_currPos++;
                } else {
                    $s4 = $this->peg_FAILED;
                    if ($this->peg_silentFails === 0) {
                        $this->peg_fail($this->peg_e25);
                    }
                }
                while ($s4 !== $this->peg_FAILED) {
                    $s3[] = $s4;
                    $s4 = $this->input_substr($this->peg_currPos, 1);
                    if (\preg_match($this->peg_c3, $s4)) {
                        $this->peg_currPos++;
                    } else {
                        $s4 = $this->peg_FAILED;
                        if ($this->peg_silentFails === 0) {
                            $this->peg_fail($this->peg_e25);
                        }
                    }
                }
                $this->peg_reportedPos = $s0;
                $s0 = $this->peg_f7();
            } else {
                $this->peg_currPos = $s0;
                $s0 = $this->peg_FAILED;
            }
        } else {
            $this->peg_currPos = $s0;
            $s0 = $this->peg_FAILED;
        }

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }

    private function peg_parse_WS(): mixed
    {
        $key = $this->peg_currPos * 13 + 12;
        $cached = $this->peg_cache[$key] ?? false;

        if ($cached) {
            $this->peg_currPos = $cached->nextPos;
            return $cached->result;
        }

        $s0 = $this->peg_currPos;
        if ($this->input_substr($this->peg_currPos, 1) === $this->peg_l22) {
            $s1 = $this->peg_l22;
            $this->peg_currPos++;
        } else {
            $s1 = $this->peg_FAILED;
            if ($this->peg_silentFails === 0) {
                $this->peg_fail($this->peg_e26);
            }
        }
        if ($s1 !== $this->peg_FAILED) {
            $this->peg_reportedPos = $s0;
            $s1 = $this->peg_f8();
        }
        $s0 = $s1;

        $this->peg_cache[$key] = new pegCacheItem($this->peg_currPos, $s0);

        return $s0;
    }
};
